/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.test.java.ROT47;

import src.main.java.ROT47.Library;


public class LibraryTest {
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        String hexadecimal = "363733326133635f6264";
        System.out.println("This is the output of: " + classUnderTest.decryption(hexadecimal));
    }
}
